openapi: 3.0.0
info:
  description: "Digital Security Platform"
  version: "1.0.0"
  title: "Banking - Origination"
  termsOfService: "https://github.com/Toblerones/Banking-Origination"
  contact:
    email: "toblerones@hotmail.com"

servers:
  - url: https://{subdomain}.com{system}
    description: Backend API
    variables:
      subdomain:
        default: toblerones
      version:
        enum:
          - v1
          - v2
        default: v1
      system:
        default: '/api'

security:
  - basicAuth: []

paths:
  /token-validation:
    post:
      security:
        - basicAuth: []
      tags:
        - Auth Token
      description: get JWT token
      parameters:
        - in: header
          name: X-Request-ID
          schema:
            type: string
          required: true
        - in: header
          name: X-Session-ID
          schema:
            type: string
          required: true
        - in: header
          name: X-Channel-ID
          schema:
            type: string
          required: true
      requestBody:
        description: data to be valided to get token
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Token'
      responses:
        '200':
          description: yes
  /token:
    post:
      tags:
        - Auth Token
      description: get JWT token
      parameters:
        - in: header
          name: X-Request-ID
          schema:
            type: string
          required: true
        - in: header
          name: X-Session-ID
          schema:
            type: string
          required: true
        - in: header
          name: X-Channel-ID
          schema:
            type: string
          required: true
      requestBody:
        description: data to be valided to get token
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationData'
      responses:
        '200':
          description: yes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
        '503':
          $ref: '#/components/responses/DownstreamError'

components:
  securitySchemes:
    basicAuth:            # arbitrary name for the security scheme
      type: http
      scheme: basic

  responses:
    InternalError:
      description: Internal Server Error (runtime)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    DownstreamError:
      description: Unknow downstream error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

    AuthenticationData:
      title: Customer Application
      type: object
      properties:
        applicationId:
          type: string
          description: application number
        customer:
          $ref: '#/components/schemas/Customer'
    Customer:
      title: Customer Info
      type: object
      properties:
        dateOfBirth:
          type: string
          description: date of birth
        mobileNumber:
          type: string
          description: mobile Number
        email:
          type: string
          description: email

    Token:
      title: token to be validated
      type: object
      properties:
        access_token:
          type: string








