/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.tobs.digital.security.platform.controller;

import com.tobs.digital.security.platform.domain.AuthenticationData;
import com.tobs.digital.security.platform.domain.Error;
import com.tobs.digital.security.platform.domain.Token;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-11-28T15:23:11.212748+11:00[Australia/Sydney]")

@Validated
@Api(value = "token", description = "the token API")
public interface TokenApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /token
     * get JWT token
     *
     * @param xRequestID  (required)
     * @param xSessionID  (required)
     * @param xChannelID  (required)
     * @param authenticationData data to be valided to get token (required)
     * @return true (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal Server Error (runtime) (status code 500)
     *         or Unknow downstream error (status code 503)
     */
    @ApiOperation(value = "", nickname = "tokenPost", notes = "get JWT token", response = Token.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "Auth Token", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "true", response = Token.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error (runtime)", response = Error.class),
        @ApiResponse(code = 503, message = "Unknow downstream error", response = Error.class) })
    @RequestMapping(value = "/token",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Token> tokenPost(@ApiParam(value = "" ,required=true) @RequestHeader(value="X-Request-ID", required=true) String xRequestID,@ApiParam(value = "" ,required=true) @RequestHeader(value="X-Session-ID", required=true) String xSessionID,@ApiParam(value = "" ,required=true) @RequestHeader(value="X-Channel-ID", required=true) String xChannelID,@ApiParam(value = "data to be valided to get token" ,required=true )  @Valid @RequestBody AuthenticationData authenticationData) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"access_token\" : \"access_token\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
