AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ddb-stream-handler

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DdbStreamHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: An Amazon DynamoDB trigger that logs the updates made to a table.
      MemorySize: 128
      Timeout: 3
      Policies: []
      PackageType: Zip
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:ap-southeast-2:297633139939:table/digital_form
            StartingPosition: LATEST
            BatchSize: 1
            Enabled: true

#  Table1:
#    Type: 'AWS::DynamoDB::Table'
#    Properties:
#      AttributeDefinitions:
#        - AttributeName: id
#          AttributeType: S
#      KeySchema:
#        - AttributeName: id
#          KeyType: HASH
#      ProvisionedThroughput:
#        ReadCapacityUnits: 5
#        WriteCapacityUnits: 5
#      StreamSpecification:
#        StreamViewType: NEW_IMAGE
