/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.tobs.origination.digital.controller;

import com.tobs.origination.digital.domain.Application;
import com.tobs.origination.digital.domain.Error;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-11-28T14:57:28.327430+11:00[Australia/Sydney]")

@Validated
@Api(value = "applications", description = "the applications API")
public interface ApplicationsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /applications/{appId} : get application
     * Return all application
     *
     * @param xRequestID  (required)
     * @param xSessionID  (required)
     * @param xChannelID  (required)
     * @param appId Unique applicaiton Id (required)
     * @return A JSON array of applications (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal Server Error (runtime) (status code 500)
     *         or Unknow downstream error (status code 503)
     */
    @ApiOperation(value = "get application", nickname = "applicationsAppIdGet", notes = "Return all application", response = Application.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "Application", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A JSON array of applications", response = Application.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error (runtime)", response = Error.class),
        @ApiResponse(code = 503, message = "Unknow downstream error", response = Error.class) })
    @RequestMapping(value = "/applications/{appId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Application> applicationsAppIdGet(@ApiParam(value = "" ,required=true) @RequestHeader(value="X-Request-ID", required=true) String xRequestID,@ApiParam(value = "" ,required=true) @RequestHeader(value="X-Session-ID", required=true) String xSessionID,@ApiParam(value = "" ,required=true) @RequestHeader(value="X-Channel-ID", required=true) String xChannelID,@ApiParam(value = "Unique applicaiton Id",required=true) @PathVariable("appId") String appId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"product\" : { \"mainCurrency\" : \"mainCurrency\", \"subCurrencies\" : [ \"subCurrencies\", \"subCurrencies\" ], \"productCodes\" : [ \"productCodes\", \"productCodes\" ] }, \"applicationId\" : \"applicationId\", \"customer\" : { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"address\" : \"address\", \"mobileNumber\" : \"mobileNumber\", \"dateOfBirth\" : \"dateOfBirth\", \"email\" : \"email\" }, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
